name: Checkout

on:
  push:
  schedule:
    - cron: "0 0 * * *" # Runs at 00:00 UTC everyday

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          date > checkout-workflow.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push