name: Horusec

on: [push, workflow_dispatch]

jobs:
  checking_code:
    runs-on: ubuntu-latest
    name: Horusec Scan
    steps:
    - name: Check out code
      uses: actions/checkout@v2.3.4
      with: # Required when commit authors is enabled
        fetch-depth: 0

    - name: Install Horusec Security
      run: curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/main/deployments/scripts/install.sh | bash -s latest

    - uses: GuillaumeFalourd/assert-command-line-output@v2
      with:
        command_line: horusec start -p="./" -e="true"
        contains: 'In this analysis, a total of 1 possible vulnerabilities were found'
        expected_result: PASSED
