name: Publish

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for the Assert Command Line Output workflow to finish
        uses: lewagon/wait-on-check-action@v1.0.0
        with:
          ref: ${{ github.ref }}
          running-workflow-name: 'Assert Command Line Output'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
          allowed-conclusions: success,skipped,cancelled
      
      - run: echo "Will run after Assert Command Line Output finished."