name: Wait on Check

on: [push]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - run: | 
          echo ${{ github.ref }}
          curl -i -u username:${{ secrets.GITHUB_TOKEN }} \
          https://api.github.com/repos/OWNER/REPO/commits/REF/check-runs \
          -H 'Accept: application/vnd.github.antiope-preview+json' | jq '[.check_runs[].name]'

  wait-on-check-1:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for the Assert Command Line Output workflow to finish
        uses: lewagon/wait-on-check-action@v1.0.0
        with:
          ref: ${{ github.ref }}
          running-workflow-name: 'Assert Command Line Output'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10

  wait-on-check-2:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Display results job (Upload Download Artifacts workflow) to succeed
        uses: lewagon/wait-on-check-action@v1.0.0
        with:
          ref: ${{ github.ref }}
          check-name: 'Display results'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10

  finish:
    needs:
      - wait-on-check-1
      - wait-on-check-2
    runs-on: ubuntu-latest
    steps:      
      - run: echo "Will run after other workflows or jobs finished."