name: Wait on Check

on: 
  push:

jobs:
  wait-on-check-1:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Multiply by 9 job (Upload & Download Artifacts workflow) to succeed
        uses: lewagon/wait-on-check-action@v1.0.0
        with:
          ref: ${{ github.ref }}
          check-name: 'Multiply by 9'
          repo-token: ${{ secrets.ACCESS_TOKEN }}
          wait-interval: 10

  wait-on-check-2:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for the Upload & Download Artifacts workflow to finish
        uses: lewagon/wait-on-check-action@v1.0.0
        with:
          ref: ${{ github.ref }}
          running-workflow-name: 'Upload & Download Artifacts'
          repo-token: ${{ secrets.ACCESS_TOKEN }}
          wait-interval: 10

  finish:
    needs:
      - wait-on-check-1
      - wait-on-check-2
    runs-on: ubuntu-latest
    steps:      
      - run: echo "Will run after other workflows or jobs finished."